In [1]:
#Loading the dataset
import os
os.getcwd()
os.chdir('C:\\Users\\user\\Desktop\\awo')
import pandas as pd
df = pd.read_csv("data.csv")
df.head(20)

,neighbourhood_group,longitude,latitude,room_type,price,minimum_nights,Neighbourhood,RoomType
0,Brooklyn,-73.97237,40.64749,Private room,149,1,1,1
1,Manhattan,-73.98377,40.75362,Entire home/apt,225,1,-1,-1
2,Manhattan,-73.94190,40.80902,Private room,150,3,-1,1
3,Brooklyn,-73.95976,40.68514,Entire home/apt,89,1,1,-1
4,Manhattan,-73.94399,40.79851,Entire home/apt,80,10,-1,-1
5,Manhattan,-73.97500,40.74767,Entire home/apt,200,3,-1,-1
6,Brooklyn,-73.95596,40.68688,Private room,60,45,1,1
7,Manhattan,-73.98493,40.76489,Private room,79,2,-1,1
8,Manhattan,-73.96723,40.80178,Private room,79,2,-1,1
9,Manhattan,-73.99037,40.71344,Entire home/apt,150,1,-1,-1
10,Manhattan,-73.96545,40.80316,Entire home/apt,135,5,-1,-1
11,Manhattan,-73.98867,40.76076,Private room,85,2,-1,1
12,Brooklyn,-73.98779,40.66829,Private room,89,4,1,1
13,Manhattan,-73.96113,40.79826,Private room,85,2,-1,1
14,Manhattan,-74.00525,40.73530,Entire home/apt,120,90,-1,-1
15,Brooklyn,-73.95352,40.70837,Entire home/apt,140,2,1,-1
16,Brooklyn,-73.97185,40.69169,Entire home/apt,215,2,1,-1
17,Manhattan,-73.99501,40.74192,Private room,140,1,-1,1
18,Brooklyn,-73.94694,40.67592,Entire home/apt,99,3,1,-1
19,Manhattan,-73.94872,40.79685,Entire home/apt,190,7,-1,-1

In [3]:
#separation  into x and y values 
x=df.iloc[:,0:-1]
y=df.iloc[:,-1] #roomtype (target values)

In [4]:
#training the model
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
#Decision tree classifier
from sklearn import tree
dt_clf=tree.DecisionTreeClassifier(max_depth=10)
dt_clf.fit(x_train, y_train)
y_pred=dt_clf.predict(x_test)
dt_clf.score(x_test,y_test)

0.8215965641829709

In [5]:
#creating the classification report
from sklearn. metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          -1       0.84      0.85      0.85      7599
           0       0.66      0.18      0.29       349
           1       0.80      0.82      0.81      6721

    accuracy                           0.82     14669
   macro avg       0.77      0.62      0.65     14669
weighted avg       0.82      0.82      0.82     14669

In [ ]:
#precision: The proportion of correct identifications among each class.
#recall: The proportion of all the correctly found positive instances.
#f1 score: The harmonic mean between the precision and recall
#support: The number of samples in each classification in each class/metric was tested on.
#accuracy: This is the percentage of labels that the model successfully predicted.
#Macro avg: This is the arithmetic mean of the individual class related to precision,memory,and f1 score.
#Weigthed avg: This is the average considering the proportion for each label in the data set.